version: '3'
services:
    web:
        image: nginx:1.15.7-alpine
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/conf/default.develop.conf:/etc/nginx/conf.d/default.conf
            - ./src:/home/www/code
        depends_on:
            - php
    php:
        build: ./docker/php
        volumes:
            - ./src:/home/www/code
        working_dir: /home/www/code
        depends_on:
            - db
    work:
      build: ./docker/php
      volumes:
        - ./src:/home/www/code
      working_dir: /home/www/code
      depends_on:
        - db
    db:
        image: mariadb:10.4.0
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: lktners_db
        volumes:
            - ./.tmp/db:/var/lib/mysql




